[package]
name = "anki"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
reqwest = "0.11"
tl = "0.7"
syn = "1.0.50"  # Newest version gives linker errors
tokio = "1.21"
regex = "1"
